// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S4_UESAN_EFCore.CodeFirst.Models;

namespace S4_UESAN_EFCore.CodeFirst.Migrations
{
    [DbContext(typeof(MundialDBContext))]
    [Migration("20210918165336_1-n SoccerPosition-Player")]
    partial class _1nSoccerPositionPlayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("S4_UESAN_EFCore.CodeFirst.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dorsal")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoccerPositionId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("SoccerPositionId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("S4_UESAN_EFCore.CodeFirst.Models.SoccerPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SoccerPosition");
                });

            modelBuilder.Entity("S4_UESAN_EFCore.CodeFirst.Models.Player", b =>
                {
                    b.HasOne("S4_UESAN_EFCore.CodeFirst.Models.SoccerPosition", "SoccerPosition")
                        .WithMany("Player")
                        .HasForeignKey("SoccerPositionId");

                    b.Navigation("SoccerPosition");
                });

            modelBuilder.Entity("S4_UESAN_EFCore.CodeFirst.Models.SoccerPosition", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
